[package]
name = "mhost"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "Like `host`, but uses multiple DNS servers massively parallel and compares results"
repository = "https://github.com/lukaspustina/mhost.git"
documentation = "http://lukaspustina.github.io/mhost"
readme = "README.md"
license = "MIT"
keywords = ["network", "dns", "host", "dig", "cli"]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]

[badges]
travis-ci = { repository = "lukaspustina/mhost", branch = "master" }
appveyor = { repository = "lukaspustina/mhost", branch = "master" }

[features]
bin = []

[[bin]]
name = "mhost"
path = "src/main.rs"
doc = false
required-features = ["bin"]

[lib]
name = "mhost"
path = "src/lib.rs"

[dependencies]
error-chain = "^0.11"
futures = "^0.1.14"
tokio-core = "^0.1.9"
trust-dns = "^0.11"
structopt = "^0.1"
structopt-derive = "^0.1"

[dev-dependencies]

